<a href="https://colab.research.google.com/github/AlexsonT/Growdev/blob/main/Ex_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# 1) Como mudar os itens do array?
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)

arr[5] = 8
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 8 6 7 8 9]


In [ ]:
# 2) Como empilhar dois arrays verticalmente?
#a = np.arange(10).reshape(2,-1)
#b = np.repeat(1, 10).reshape(2,-1)
# Saída desejada:
# array([
# [0, 1, 2, 3, 4],
# [5, 6, 7, 8, 9],
# [1, 1, 1, 1, 1],
# [1, 1, 1, 1, 1]])

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

c = np.concatenate((a,b))
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
# 3) Como empilhar dois arrays horizontalmente?
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
# Saída desejada:
# array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
# [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [ ]:
# 4) Como criar a seguinte sequência com numpy.
# a = np.array([1,2,3])
# Saída desejada:
# # array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

a = np.array([1,2,3])

b = np.repeat(a, 3 , axis = None)
c = np.tile(a, 3)

d = np.concatenate((b,c))

print(d)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [ ]:
# 5) Como pegar os elementos em comum entre dois arrays?
# Entrada:
# a = np.array([1,2,3,2,3,4,3,4,5,6])

# b = np.array([7,2,10,2,7,4,9,4,9,8])
# Saída desejada:
# array([2, 4])

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

c = np.intersect1d(a, b)
print(c)

[2 4]


In [ ]:
# 6) Como pegar as posições de elementos iguais entre dois arrays?
# Entrada:
# a = np.array([1,2,3,2,3,4,3,4,5,6])
# b = np.array([7,2,10,2,7,4,9,4,9,8])
# Saída desejada:
# (array([1, 3, 5, 7]),)

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

c = np.where(a == b)

print(c)

(array([1, 3, 5, 7]),)


In [ ]:
# 7) Como extrair todos os números em um intervalo desejado?
# Entrada:
# a = np.array([2, 6, 1, 9, 10, 3, 27])
# Saída desejada:
# (array([6, 9, 10]),)

a = np.array([2, 6, 1, 9, 10, 3, 27])

b = a[np.array([1, 3, 4])]

print(b)

[ 6  9 10]


In [11]:
# 8) Como transformar um array 2D em um array 1D, crie um array 2D com uma quantidade arbitrária de linhas e colunas e transforme em um array 1D.

array2d = np.arange(8).reshape(2,-1)

array1d = a.flatten()

print(array2d)
print(array1d)

[[0 1 2 3]
 [4 5 6 7]]
[0 1 2 3 4 5 6 7]


In [ ]:
# 9) Crie uma ufunc para transformar uma imagem colorida em uma imagem em escala de cinza e aplique em um programa.



In [ ]:
# 10) O seguinte link contém imagens comparativas dos registros dos telescópios Hubble e James Webb de diferentes partes do cosmos. Faça o download das imagens de um dos registros escolhidos, carregue a imagem com o opencv, e realize os seguintes processamentos.
# a) Crie e aplique filtros para exibir as imagens em cores vermelho, verde e azul separadamente, para que possamos observar esses espectros da luz visível separadamente.

# b) Crie e aplique um filtro que procure exibir somente (ou quase isso) os pontos mais brilhantes da imagem (normalmente estrelas ou galáxias)